/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as ApiPublicBridgeStrategiesRouteImport } from './routes/api/public/bridge/strategies'
import { Route as ApiPublicBridgeHeartbeatRouteImport } from './routes/api/public/bridge/heartbeat'
import { Route as ApiPublicBridgeCommandsRouteImport } from './routes/api/public/bridge/commands'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBridgeStrategiesRoute =
  ApiPublicBridgeStrategiesRouteImport.update({
    id: '/api/public/bridge/strategies',
    path: '/api/public/bridge/strategies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeHeartbeatRoute =
  ApiPublicBridgeHeartbeatRouteImport.update({
    id: '/api/public/bridge/heartbeat',
    path: '/api/public/bridge/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeCommandsRoute = ApiPublicBridgeCommandsRouteImport.update({
  id: '/api/public/bridge/commands',
  path: '/api/public/bridge/commands',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/bridge/commands': typeof ApiPublicBridgeCommandsRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/strategies': typeof ApiPublicBridgeStrategiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/bridge/commands': typeof ApiPublicBridgeCommandsRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/strategies': typeof ApiPublicBridgeStrategiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/bridge/commands': typeof ApiPublicBridgeCommandsRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/strategies': typeof ApiPublicBridgeStrategiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/dashboard'
    | '/logs'
    | '/strategies'
    | '/api/public/bridge/commands'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/dashboard'
    | '/logs'
    | '/strategies'
    | '/api/public/bridge/commands'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/strategies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/logs'
    | '/_authenticated/strategies'
    | '/api/public/bridge/commands'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/strategies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBridgeCommandsRoute: typeof ApiPublicBridgeCommandsRoute
  ApiPublicBridgeHeartbeatRoute: typeof ApiPublicBridgeHeartbeatRoute
  ApiPublicBridgeStrategiesRoute: typeof ApiPublicBridgeStrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bridge/strategies': {
      id: '/api/public/bridge/strategies'
      path: '/api/public/bridge/strategies'
      fullPath: '/api/public/bridge/strategies'
      preLoaderRoute: typeof ApiPublicBridgeStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/heartbeat': {
      id: '/api/public/bridge/heartbeat'
      path: '/api/public/bridge/heartbeat'
      fullPath: '/api/public/bridge/heartbeat'
      preLoaderRoute: typeof ApiPublicBridgeHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/commands': {
      id: '/api/public/bridge/commands'
      path: '/api/public/bridge/commands'
      fullPath: '/api/public/bridge/commands'
      preLoaderRoute: typeof ApiPublicBridgeCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBridgeCommandsRoute: ApiPublicBridgeCommandsRoute,
  ApiPublicBridgeHeartbeatRoute: ApiPublicBridgeHeartbeatRoute,
  ApiPublicBridgeStrategiesRoute: ApiPublicBridgeStrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
